version: '0.5.2.2_{build}-{branch}'

environment:
  ANDROID_HOME: C:\android-sdk-windows

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - appveyor DownloadFile https://dl.google.com/android/repository/sdk-tools-windows-4333796.zip
  - 7z x sdk-tools-windows-4333796.zip -oC:\android-sdk-windows > nul
  - yes | C:\android-sdk-windows\tools\bin\sdkmanager.bat --licenses > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platforms;android-28" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "platform-tools" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "build-tools;28.0.3" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "cmake;3.6.4111459" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "patcher;v4" > nul
  - C:\android-sdk-windows\tools\bin\sdkmanager.bat "ndk;22.0.7026061" --channel=1 > nul
  - set PATH=%PATH%;C:\android-sdk-windows\ndk-bundle;C:\android-sdk-windows\build-tools\28.0.3

build_script:
  - gradlew.bat :edxp-core:zipRelease
  - gradlew.bat :edxp-core:zipDebug

artifacts:
  - path: 'edxp-core\release\**\*.zip'

pull_requests:
  do_not_increment_build_number: true

skip_tags: true

only_commits:
  files:
    - dalvikdx/
    - dexmaker/
    - edxp-common/
    - edxp-core/
    - edxp-sandhook/
    - edxp-service/
    - edxp-yahfa/
    - hiddenapi-stubs/
    - sandhook-annotation/
    - sandhook-hooklib/
    - xposed-bridge/
    - .gitmodules
    - appveyor.yml
    - build.gradle
    - gradle.properties
    - settings.gradle
